name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Allow undefined macros (m4)
        run: echo "m4_pattern_allow([LT_SYS_SYMBOL_USCORE])" >> configure.ac || true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip zip unzip openjdk-17-jdk \
            build-essential libtool automake autoconf pkg-config \
            libncurses5 m4 git

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython virtualenv
          pip install buildozer

      - name: Set environment variables
        run: |
          echo "PATH=$HOME/.buildozer/android/platform/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug
