name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk \
            python3-pip build-essential git libtool \
            autoconf automake m4 pkg-config

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install cython virtualenv buildozer

      - name: Patch m4 macro (to avoid LT_SYS_SYMBOL_USCORE error)
        run: echo 'm4_pattern_allow([LT_SYS_SYMBOL_USCORE])' >> dummy.ac

      - name: Build APK
        run: |
          buildozer android debug
