name: Build Android APK

on:
  push:
    branches:
      - main  # 或 master，看你的默认分支
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk build-essential wget
          pip install --upgrade pip
          pip install cython virtualenv
          pip install buildozer

      - name: Install Android SDK Build Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug
